### ISSUE TITLE
cargo-deny: command not found.

### ISSUE THREAD

**Issue by mainrs** [DeterminateSystems/nix-github-actions#1]
I am not entirely sure why this is the case. I even explicitly state that I use the latest unstable channel:

```yaml
steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
```

I do run the workflow locally using `act`.
